### Post request to create a patient
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Faisal Mohamed Adan",
  "email": "kafka_test12223@example.com",
  "address": "332 street nairobi",
  "dateOfBirth": "2001-01-12",
  "registeredDate": "2025-01-22"
}


###