### Update an existing  patient
PUT http://localhost:4004/api/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Faisal Abdi updated",
  "email": "isabella.walker2@example.com",
  "address": "332 street kuma",
  "dateOfBirth": "2001-01-12"
}

###